import type { Branch, Brand, VehicleCategory, Vehicle, UsedVehicle, BranchStaff } from './types';

export const mockBranches: Branch[] = [
  {
    id: 'branch-1',
    name: 'Las Condes',
    type: 'both',
    address: 'Av. Las Condes 7890',
    city: 'Santiago',
    region: 'Región Metropolitana',
    phone: '22 706 4400',
    email: 'contacto@melhuish.cl',
    hours_weekday: 'Lunes a Viernes 9:00 - 19:00',
    hours_saturday: 'Sábado 9:00 - 14:00',
    hours_sunday: null,
    latitude: null,
    longitude: null,
    services: ['sales', 'service'],
    brands_served: ['chevrolet', 'dongfeng', 'foton'],
    created_at: new Date().toISOString(),
  },
  {
    id: 'branch-2',
    name: 'Mall Paseo Quilín',
    type: 'both',
    address: 'Mar Tirreno 3349, Espacio E4',
    city: 'Santiago',
    region: 'Región Metropolitana',
    phone: '22 706 4400',
    email: null,
    hours_weekday: 'Lunes a Domingo 10:00 - 20:00',
    hours_saturday: 'Sábado 10:00 - 20:00',
    hours_sunday: 'Domingo 10:00 - 20:00',
    latitude: null,
    longitude: null,
    services: ['sales', 'service'],
    brands_served: ['chevrolet', 'dongfeng', 'foton'],
    created_at: new Date().toISOString(),
  },
];

export const mockBrands: Brand[] = [
  { id: 'brand-1', name: 'Chevrolet', logo_url: null, slug: 'chevrolet', order: 1, created_at: new Date().toISOString() },
  { id: 'brand-2', name: 'Dongfeng', logo_url: null, slug: 'dongfeng', order: 2, created_at: new Date().toISOString() },
  { id: 'brand-3', name: 'Foton', logo_url: null, slug: 'foton', order: 3, created_at: new Date().toISOString() },
];

export const mockVehicleCategories: VehicleCategory[] = [
  { id: 'cat-1', name: 'SUV', slug: 'suv', created_at: new Date().toISOString() },
  { id: 'cat-2', name: 'Pickup', slug: 'pickup', created_at: new Date().toISOString() },
  { id: 'cat-3', name: 'Sedan', slug: 'sedan', created_at: new Date().toISOString() },
];

const now = () => new Date().toISOString();

export const mockVehicles: Vehicle[] = [
  // Chevrolet
  {
    id: 'v-chev-1',
    brand_id: 'brand-1',
    category_id: 'cat-1',
    name: 'Tracker',
    version: 'LTZ',
    slug: 'chevrolet-tracker-ltz',
    image_url: 'https://images.pexels.com/photos/3802510/pexels-photo-3802510.jpeg?auto=compress&cs=tinysrgb&w=600',
    price_list: 18990000,
    price_financing: 499000,
    includes_iva: false,
    fuel_type: 'Bencina',
    transmission: 'Automática',
    description: 'SUV compacto con tecnología y confort.',
    features: {},
    is_active: true,
    order: 1,
    created_at: now(),
    updated_at: now(),
  },
  {
    id: 'v-chev-2',
    brand_id: 'brand-1',
    category_id: 'cat-2',
    name: 'S10',
    version: 'LTZ 2.8 Turbo Diesel',
    slug: 'chevrolet-s10-ltz',
    image_url: 'https://images.pexels.com/photos/3764983/pexels-photo-3764983.jpeg?auto=compress&cs=tinysrgb&w=600',
    price_list: 24990000,
    price_financing: 649000,
    includes_iva: false,
    fuel_type: 'Diesel',
    transmission: 'Automática',
    description: 'Pickup robusta para trabajo y aventura.',
    features: {},
    is_active: true,
    order: 2,
    created_at: now(),
    updated_at: now(),
  },
  {
    id: 'v-chev-3',
    brand_id: 'brand-1',
    category_id: 'cat-3',
    name: 'Onix',
    version: 'Plus',
    slug: 'chevrolet-onix-plus',
    image_url: 'https://images.pexels.com/photos/3802510/pexels-photo-3802510.jpeg?auto=compress&cs=tinysrgb&w=600',
    price_list: 12990000,
    price_financing: 349000,
    includes_iva: false,
    fuel_type: 'Bencina',
    transmission: 'Manual',
    description: 'Sedan eficiente y espacioso.',
    features: {},
    is_active: true,
    order: 3,
    created_at: now(),
    updated_at: now(),
  },
  {
    id: 'v-chev-4',
    brand_id: 'brand-1',
    category_id: 'cat-1',
    name: 'Captiva',
    version: 'Premier',
    slug: 'chevrolet-captiva-premier',
    image_url: 'https://images.pexels.com/photos/3764983/pexels-photo-3764983.jpeg?auto=compress&cs=tinysrgb&w=600',
    price_list: 27990000,
    price_financing: 729000,
    includes_iva: false,
    fuel_type: 'Bencina',
    transmission: 'Automática',
    description: 'SUV familiar con amplio espacio.',
    features: {},
    is_active: true,
    order: 4,
    created_at: now(),
    updated_at: now(),
  },
  // Dongfeng
  {
    id: 'v-dong-1',
    brand_id: 'brand-2',
    category_id: 'cat-1',
    name: 'Rich 6',
    version: 'Premium',
    slug: 'dongfeng-rich-6-premium',
    image_url: 'https://images.pexels.com/photos/3802510/pexels-photo-3802510.jpeg?auto=compress&cs=tinysrgb&w=600',
    price_list: 15990000,
    price_financing: 419000,
    includes_iva: false,
    fuel_type: 'Bencina',
    transmission: 'Automática',
    description: 'SUV urbano con diseño moderno.',
    features: {},
    is_active: true,
    order: 10,
    created_at: now(),
    updated_at: now(),
  },
  {
    id: 'v-dong-2',
    brand_id: 'brand-2',
    category_id: 'cat-2',
    name: 'Rich 6 Pickup',
    version: 'Doble Cabina',
    slug: 'dongfeng-rich-6-pickup',
    image_url: 'https://images.pexels.com/photos/3764983/pexels-photo-3764983.jpeg?auto=compress&cs=tinysrgb&w=600',
    price_list: 16990000,
    price_financing: 449000,
    includes_iva: false,
    fuel_type: 'Diesel',
    transmission: 'Manual',
    description: 'Pickup versátil para trabajo diario.',
    features: {},
    is_active: true,
    order: 11,
    created_at: now(),
    updated_at: now(),
  },
  {
    id: 'v-dong-3',
    brand_id: 'brand-2',
    category_id: 'cat-3',
    name: 'A30',
    version: 'Comfort',
    slug: 'dongfeng-a30-comfort',
    image_url: 'https://images.pexels.com/photos/3802510/pexels-photo-3802510.jpeg?auto=compress&cs=tinysrgb&w=600',
    price_list: 11990000,
    price_financing: 319000,
    includes_iva: false,
    fuel_type: 'Bencina',
    transmission: 'Manual',
    description: 'Sedan económico y confiable.',
    features: {},
    is_active: true,
    order: 12,
    created_at: now(),
    updated_at: now(),
  },
  {
    id: 'v-dong-4',
    brand_id: 'brand-2',
    category_id: 'cat-1',
    name: 'Fengon 580',
    version: 'Pro',
    slug: 'dongfeng-fengon-580-pro',
    image_url: 'https://images.pexels.com/photos/3764983/pexels-photo-3764983.jpeg?auto=compress&cs=tinysrgb&w=600',
    price_list: 19990000,
    price_financing: 529000,
    includes_iva: false,
    fuel_type: 'Bencina',
    transmission: 'Automática',
    description: 'SUV 7 plazas para la familia.',
    features: {},
    is_active: true,
    order: 13,
    created_at: now(),
    updated_at: now(),
  },
  // Foton
  {
    id: 'v-fot-1',
    brand_id: 'brand-3',
    category_id: 'cat-2',
    name: 'Tunland',
    version: 'E5',
    slug: 'foton-tunland-e5',
    image_url: 'https://images.pexels.com/photos/3764983/pexels-photo-3764983.jpeg?auto=compress&cs=tinysrgb&w=600',
    price_list: 14990000,
    price_financing: 399000,
    includes_iva: false,
    fuel_type: 'Diesel',
    transmission: 'Manual',
    description: 'Pickup comercial de gran capacidad.',
    features: {},
    is_active: true,
    order: 20,
    created_at: now(),
    updated_at: now(),
  },
  {
    id: 'v-fot-2',
    brand_id: 'brand-3',
    category_id: 'cat-2',
    name: 'View',
    version: 'Doble Cabina',
    slug: 'foton-view-doble-cabina',
    image_url: 'https://images.pexels.com/photos/3802510/pexels-photo-3802510.jpeg?auto=compress&cs=tinysrgb&w=600',
    price_list: 12990000,
    price_financing: 349000,
    includes_iva: false,
    fuel_type: 'Diesel',
    transmission: 'Manual',
    description: 'Pickup ideal para trabajo y carga.',
    features: {},
    is_active: true,
    order: 21,
    created_at: now(),
    updated_at: now(),
  },
  {
    id: 'v-fot-3',
    brand_id: 'brand-3',
    category_id: 'cat-1',
    name: 'Sauvana',
    version: 'Premium',
    slug: 'foton-sauvana-premium',
    image_url: 'https://images.pexels.com/photos/3764983/pexels-photo-3764983.jpeg?auto=compress&cs=tinysrgb&w=600',
    price_list: 17990000,
    price_financing: 469000,
    includes_iva: false,
    fuel_type: 'Diesel',
    transmission: 'Automática',
    description: 'SUV comercial y espacioso.',
    features: {},
    is_active: true,
    order: 22,
    created_at: now(),
    updated_at: now(),
  },
  {
    id: 'v-fot-4',
    brand_id: 'brand-3',
    category_id: 'cat-2',
    name: 'Thunder',
    version: 'Pro',
    slug: 'foton-thunder-pro',
    image_url: 'https://images.pexels.com/photos/3802510/pexels-photo-3802510.jpeg?auto=compress&cs=tinysrgb&w=600',
    price_list: 21990000,
    price_financing: 579000,
    includes_iva: false,
    fuel_type: 'Diesel',
    transmission: 'Automática',
    description: 'Pickup premium para uso intensivo.',
    features: {},
    is_active: true,
    order: 23,
    created_at: now(),
    updated_at: now(),
  },
];

export const mockUsedVehicles: UsedVehicle[] = [];

export const mockBranchStaff: BranchStaff[] = [];

export function getBranchesByType(type: 'sales' | 'service' | 'both'): Branch[] {
  return mockBranches.filter((b) => b.type === type || b.type === 'both');
}
